void cleaf_apply_css(void) {
    static const char *css =
        "window.cleaf-window,"
        "window.cleaf-window > contents,"
        "window.cleaf-window > contents > *,"
        "window.cleaf-window decoration,"
        "window.cleaf-window:backdrop decoration {"
        "  border-radius: 0;"
        "  border-top-left-radius: 0;"
        "  border-top-right-radius: 0;"
        "  border-bottom-left-radius: 0;"
        "  border-bottom-right-radius: 0;"
        "  box-shadow: none;"
        "}"
        ".cleaf-root, .cleaf-root * {"
        "  border-radius: 0;"
        "  border-top-left-radius: 0;"
        "  border-top-right-radius: 0;"
        "  border-bottom-left-radius: 0;"
        "  border-bottom-right-radius: 0;"
        "  box-shadow: none;"
        "}"
        ".cleaf-root box, .cleaf-root paned, .cleaf-root stack,"
        ".cleaf-root revealer, .cleaf-root frame, .cleaf-root viewport,"
        ".cleaf-root scrolledwindow, .cleaf-root textview,"
        ".cleaf-root textview text, .cleaf-root listbox,"
        ".cleaf-root listbox row, .cleaf-root notebook,"
        ".cleaf-root notebook * {"
        "  border-radius: 0;"
        "  box-shadow: none;"
        "}"
        "scrolledwindow.cleaf-editor-scroll,"
        "scrolledwindow.cleaf-minimap-scroll,"
        ".cleaf-tab-page,"
        ".cleaf-editor-area,"
        ".cleaf-editor-overlay,"
        "textview.cleaf-editor,"
        "textview.cleaf-editor text,"
        "textview.cleaf-minimap,"
        "textview.cleaf-minimap text,"
        "textview.cleaf-preview,"
        "textview.cleaf-preview text,"
        ".cleaf-root viewport,"
        ".cleaf-root notebook,"
        ".cleaf-root notebook > stack {"
        "  border-radius: 0;"
        "  box-shadow: none;"
        "  border: none;"
        "}"
        ".cleaf-top {"
        "  border-bottom: 1px solid alpha(currentColor, 0.18);"
        "  padding: 3px 6px;"
        "}"
        ".cleaf-title { font-weight: 600; padding-left: 14px; padding-right: 10px; }"
        ".cleaf-root notebook { border: none; }"
        ".cleaf-root notebook > header { border: none; }"
        ".cleaf-root notebook > header.top { border-bottom: 1px solid alpha(currentColor, 0.18); }"
        ".cleaf-root notebook > header.top > tabs > tab {"
        "  min-height: 34px;"
        "  padding: 0;"
        "  margin: 0 1px 0 0;"
        "  border: none;"
        "  border-right: 1px solid alpha(currentColor, 0.12);"
        "  border-radius: 0;"
        "  box-shadow: none;"
        "}"
        ".cleaf-root notebook > header.top > tabs > tab * { border-radius: 0; box-shadow: none; }"
        ".cleaf-root notebook > header.top > tabs > tab:checked { border-bottom: 2px solid #8bd5ca; }"
        ".cleaf-tab { padding: 6px 16px; min-width: 160px; }"
        ".cleaf-tab-close {"
        "  padding: 0 4px;"
        "  min-width: 18px;"
        "  min-height: 18px;"
        "  border: none;"
        "  background: transparent;"
        "}"
        ".cleaf-tab-close:hover { border-radius: 0; }"
        ".cleaf-root textview border { color: alpha(currentColor, 0.55); }"
        ".cleaf-gutter { }"
        ".cleaf-minimap, .cleaf-minimap text { font-family: monospace; font-size: 2.6pt; }"
        ".cleaf-preview, .cleaf-preview text { font-size: 11pt; }"
        "scrolledwindow.cleaf-preview-scroll { border-left: 1px solid alpha(currentColor, 0.18); }"
        ".cleaf-project-pane { border-right: 1px solid alpha(currentColor, 0.18); }"
        ".cleaf-project-section { font-size: 9pt; }"
        ".cleaf-project-hint { opacity: 0.65; font-size: 8pt; padding-bottom: 3px; }"
        ".cleaf-project-tree { padding: 6px; border: none; }"
        ".cleaf-project-tree row { min-height: 24px; }"
        ".cleaf-project-icon { opacity: 0.78; font-size: 10pt; }"
        ".cleaf-git-status { font-weight: 800; min-width: 18px; opacity: 1.0; }"
        ".cleaf-git-status-modified { color: #f9c74f; }"
        ".cleaf-git-status-added { color: #57cc99; }"
        ".cleaf-git-status-deleted { color: #ff6b6b; }"
        ".cleaf-git-status-renamed { color: #4cc9f0; }"
        ".cleaf-git-status-conflict { color: #ff4d6d; }"
        ".cleaf-git-status-untracked { color: #77bdfb; }"
        ".cleaf-git-status-staged { color: #cba6f7; }"
        ".cleaf-search-panel { border-top: 1px solid alpha(currentColor, 0.18); padding: 5px 8px; }"
        ".cleaf-tool-panel { border-top: 1px solid alpha(currentColor, 0.18); padding: 5px 8px; min-height: 34px; }"
        ".cleaf-tool-title { opacity: 0.72; font-size: 8pt; font-weight: 700; padding: 0 4px; }"
        ".cleaf-bottom { border-top: 1px solid alpha(currentColor, 0.18); padding: 3px 6px; }"
        ".cleaf-bottom-controls { border: none; min-height: 34px; }"
        ".cleaf-bottom-strip { padding: 0 2px; }"
        ".cleaf-bottom-group { padding: 0 2px; }"
        ".cleaf-bottom-title { opacity: 0.68; font-size: 8pt; font-weight: 700; padding: 0 4px; }"
        ".cleaf-switch-row { padding: 0 1px; }"
        ".cleaf-switch-label { opacity: 0.82; font-size: 8.5pt; padding: 0 2px; }"
        ".cleaf-status { opacity: 0.85; padding: 3px 6px; }"
        ".cleaf-codex-panel {"
        "  border-left: 1px solid alpha(currentColor, 0.18);"
        "  padding: 8px;"
        "}"
        ".cleaf-codex-status { opacity: 0.68; font-size: 8.5pt; }"
        ".cleaf-codex-panel textview { font-size: 10pt; }"
        ".cleaf-codex-panel scrolledwindow {"
        "  border: 1px solid alpha(currentColor, 0.16);"
        "}"
        ".cleaf-codex-approval {"
        "  border: 1px solid #d6a84b;"
        "  background: alpha(#d6a84b, 0.10);"
        "  padding: 8px;"
        "}"
        ".cleaf-codex-review {"
        "  border: 1px solid alpha(#77bdfb, 0.55);"
        "  background: alpha(#77bdfb, 0.08);"
        "  padding: 8px;"
        "}"
        ".cleaf-indent-status { opacity: 0.72; padding: 3px 8px; }"
        ".cleaf-menu-title { font-weight: 600; padding: 4px 2px; }"
        ".cleaf-pref-tab { padding: 4px 14px; }"
        ".cleaf-menu-small { opacity: 0.75; padding: 2px 2px; }"
        "button.cleaf-flat {"
        "  padding: 3px 8px;"
        "  border-radius: 0;"
        "  background: transparent;"
        "}"
        "button.cleaf-flat:hover { background: alpha(currentColor, 0.10); }"
        ".cleaf-root button { padding: 4px 8px; border-radius: 0; }"
        ".cleaf-root button:hover { border-radius: 0; }"
        ".cleaf-root entry { min-height: 24px; border-radius: 0; }"
        ".cleaf-root dropdown, .cleaf-root combobox, .cleaf-root switch { border-radius: 0; }"
        ".cleaf-root popover, .cleaf-root popover contents, .cleaf-root menu, .cleaf-root menuitem { border-radius: 0; box-shadow: none; }"
        "popover.cleaf-completion-popover,"
        "popover.cleaf-hover-popover,"
        "popover.cleaf-context-popover,"
        "popover.cleaf-tools-popover {"
        "  border: none;"
        "  border-radius: 0;"
        "  box-shadow: none;"
        "}"
        "popover.cleaf-completion-popover contents,"
        "popover.cleaf-hover-popover contents,"
        "popover.cleaf-context-popover contents,"
        "popover.cleaf-tools-popover contents {"
        "  border: none;"
        "  border-radius: 0;"
        "  padding: 0;"
        "  box-shadow: none;"
        "}"
        "popover.cleaf-completion-popover, popover.cleaf-hover-popover,"
        "popover.cleaf-context-popover, popover.cleaf-tools-popover {"
        "  background-clip: border-box;"
        "}"
        "popover.cleaf-completion-popover arrow,"
        "popover.cleaf-hover-popover arrow,"
        "popover.cleaf-context-popover arrow,"
        "popover.cleaf-tools-popover arrow {"
        "  border: none;"
        "  background: transparent;"
        "  box-shadow: none;"
        "}"
        ".cleaf-completion-scroll { border: none; }"
        ".cleaf-completion-list, .cleaf-ref-list { border: none; border-radius: 0; }"
        ".cleaf-completion-list row, .cleaf-ref-list row { border-radius: 0; padding: 1px; }"
        ".cleaf-completion-list row:selected { background: #89b4fa; color: #11111b; }"
        ".cleaf-completion-title { font-family: monospace; font-weight: 650; }"
        ".cleaf-completion-detail { opacity: 0.72; font-size: 8.5pt; font-family: monospace; }"
        ".cleaf-ref-list row:hover { background: alpha(currentColor, 0.10); }"
        ".cleaf-ref-heading { color: #cba6f7; font-weight: 700; }"
        ".cleaf-ref-title { color: #89dceb; font-family: monospace; font-weight: 600; }"
        ".cleaf-ref-kind { opacity: 0.72; font-style: italic; font-size: 8.5pt; }"
        ".cleaf-ref-snippet { font-family: monospace; font-size: 9pt; }"
        ".cleaf-color-label { padding: 4px; }";
    GtkCssProvider *provider = gtk_css_provider_new();
    gtk_css_provider_load_from_string(provider, css);
    gtk_style_context_add_provider_for_display(
        gdk_display_get_default(), GTK_STYLE_PROVIDER(provider),
        GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
    g_object_unref(provider);
}
